// Legacy exporter interop for issue #92; migrate the complete serializer with
// the public MEFF path after the typed editor/persistence boundary is ready.
// @ts-expect-error Existing MEFF serializer is untyped first-party JavaScript.
import { exportMeff } from '../../lib/export/Meff.js';
import { importMeffToModelDto } from './meff-import.js';
import { toMeffShape } from './meff-export-shape.js';
import { serializeModelDto, validateModelDto } from './validate.js';
import type { ModelDto, ViewNodeDto } from './types.js';

function exportFailure(): never {
  const error = new TypeError('Unable to export the ArchiMate model DTO as MEFF.');
  Object.assign(error, { code: 'MEFF_DTO_EXPORT_INVALID' });
  throw error;
}

function sameData(input: unknown, projected: unknown): boolean {
  if (Object.is(input, projected)) return true;
  if (Array.isArray(input) || Array.isArray(projected)) {
    return Array.isArray(input) && Array.isArray(projected) &&
      input.length === projected.length && input.every((item, index) => sameData(item, projected[index]));
  }
  if (!input || !projected || typeof input !== 'object' || typeof projected !== 'object') return false;
  const source = input as Record<string, unknown>;
  const target = projected as Record<string, unknown>;
  const keys = Reflect.ownKeys(source).filter((key) => source[key as string] !== undefined);
  const expected = Reflect.ownKeys(target).filter((key) => target[key as string] !== undefined);
  return keys.length === expected.length && keys.every((key) =>
    Reflect.has(target, key) && sameData(source[key as string], target[key as string]));
}

function xmlEscape(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/** Insert only MEFF diagram labels into XML generated by our existing serializer. */
function withDiagramLabels(xml: string, dto: ModelDto): string {
  const byView = new Map<string, Map<string, string>>();
  for (const view of dto.views) {
    const labels = new Map<string, string>();
    const collect = (node: ViewNodeDto): void => {
      if (node.label !== undefined) labels.set(`node:${node.id}`, node.label);
      node.nodes.forEach(collect);
    };
    view.nodes.forEach(collect);
    for (const connection of view.connections) {
      if (connection.label !== undefined) labels.set(`connection:${connection.id}`, connection.label);
    }
    if (labels.size) byView.set(view.id, labels);
  }
  if (!byView.size) return xml;
  const matchedViews = new Set<string>();
  const result = xml.replace(/(<view\b[^>]*\bidentifier="([^"]+)"[^>]*>)([\s\S]*?)(<\/view>)/g,
    (full, open: string, viewId: string, body: string, close: string) => {
      const labels = byView.get(viewId);
      if (!labels) return full;
      if (matchedViews.has(viewId)) return exportFailure();
      matchedViews.add(viewId);
      const found = new Set<string>();
      const labeledBody = body.replace(/<(node|connection)\b[^>]*\bidentifier="([^"]+)"[^>]*>/g,
        (tag, kind: string, id: string) => {
          const key = `${kind}:${id}`;
          if (!labels.has(key)) return tag;
          if (tag.endsWith('/>') || found.has(key)) return exportFailure();
          found.add(key);
          return tag + '<label>' + xmlEscape(labels.get(key)!) + '</label>';
        });
      if (found.size !== labels.size) return exportFailure();
      return open + labeledBody + close;
    });
  if (matchedViews.size !== byView.size) return exportFailure();
  return result;
}

/** Fail closed if the supported DTO subset cannot survive a MEFF round trip. */
export function exportModelDtoToMeff(input: unknown): string {
  try {
    const dto = validateModelDto(input);
    if (dto.diagnostics.length || !sameData(input, dto)) return exportFailure();
    const result: unknown = exportMeff(toMeffShape(dto));
    if (!result || typeof result !== 'object' || !('xml' in result) ||
        typeof result.xml !== 'string' || !('diagnostics' in result) ||
        !Array.isArray(result.diagnostics) || result.diagnostics.length) return exportFailure();
    const xml = withDiagramLabels(result.xml, dto);
    const reparsed = importMeffToModelDto(xml);
    if (reparsed.diagnostics.length || serializeModelDto(reparsed) !== serializeModelDto(dto)) {
      return exportFailure();
    }
    return xml;
  } catch {
    return exportFailure();
  }
}
