// Generated by scripts/build-relationship-semantics-adapter.mts from lib/util/RelationshipSemanticsAdapter.mts.
// Do not edit by hand; run npm run generate:relationship-semantics-adapter.
import { validateRelationshipSemantics } from '../../dist/language/relationship-semantics.mjs';
export function decideRelationshipSemantics(sourceType, relationshipType, targetType, sourceKind = 'element', targetKind = 'element') {
    return validateRelationshipSemantics({
        sourceType,
        relationshipType,
        targetType,
        sourceKind,
        targetKind
    });
}
