// Generated by scripts/build-legacy-relationship-util.mts from lib/util/RelationshipUtil.mts.
// Do not edit by hand; run npm run generate:legacy-relationship-util.
// @ts-expect-error Legacy JavaScript utility; migrated separately.
import { getRelationshipMap, is } from './ModelUtil.js';
import { RELATIONSHIP_SEMANTIC_ROWS } from './relationship-semantic-projection.mjs';
const relationTab = Object.freeze({
    s: 'Specialization',
    c: 'Composition',
    g: 'Aggregation',
    i: 'Assignment',
    r: 'Realization',
    v: 'Serving',
    a: 'Access',
    n: 'Influence',
    t: 'Triggering',
    f: 'Flow',
    o: 'Association'
});
const reviewedRows = RELATIONSHIP_SEMANTIC_ROWS;
function semanticType(relationshipType) {
    return relationshipType.endsWith('Relationship') ? relationshipType : `${relationshipType}Relationship`;
}
function legacyType(relationshipType) {
    return relationshipType.replace(/Relationship$/, '');
}
function reviewedRowsForPair(sourceType, targetType) {
    return reviewedRows.filter((row) => row.sourceType === sourceType && row.targetType === targetType);
}
export function getRelationshipsAllowed(sourceType, targetType, excludedRelationType) {
    if (!sourceType || !targetType)
        return [];
    const rows = reviewedRowsForPair(sourceType, targetType);
    if (rows.length > 0) {
        return rows
            .filter((row) => row.decision === 'allowed')
            .map((row) => Object.values(relationTab).find((type) => type === legacyType(row.relationshipType)))
            .filter((relationship) => relationship !== undefined)
            .filter((relationship) => relationship !== excludedRelationType);
    }
    const sourceRelationshipMap = getRelationshipMap(sourceType);
    const allowedCodes = sourceRelationshipMap?.get(targetType);
    if (!allowedCodes)
        return [];
    return Array.from(allowedCodes, (code) => relationTab[code] ?? '')
        .filter((relationship) => relationship !== '' && relationship !== excludedRelationType);
}
export function isRelationshipAllowed(sourceType, targetType, relationshipType) {
    if (!sourceType || !targetType || !relationshipType)
        return false;
    const rows = reviewedRowsForPair(sourceType, targetType);
    if (rows.length > 0) {
        return rows.some((row) => row.relationshipType === semanticType(relationshipType) && row.decision === 'allowed');
    }
    const sourceRelationshipMap = getRelationshipMap(sourceType);
    const allowedCodes = sourceRelationshipMap?.get(targetType);
    if (!allowedCodes)
        return false;
    return Array.from(allowedCodes, (code) => relationTab[code] ?? '')
        .some((relationship) => relationship === legacyType(relationshipType));
}
export function getExistingRelationships(source, target, relationshipsNode, currentRelationshipRef) {
    const sourceBusinessObject = source.businessObject;
    const targetBusinessObject = target.businessObject;
    let sourceRefId;
    let targetRefId;
    if (is(sourceBusinessObject, 'archimate:Node'))
        sourceRefId = sourceBusinessObject?.elementRef?.id;
    if (is(sourceBusinessObject, 'archimate:Connection'))
        sourceRefId = sourceBusinessObject?.relationshipRef?.id;
    if (is(targetBusinessObject, 'archimate:Node'))
        targetRefId = targetBusinessObject?.elementRef?.id;
    if (is(targetBusinessObject, 'archimate:Connection'))
        targetRefId = targetBusinessObject?.relationshipRef?.id;
    const relationships = relationshipsNode?.relationships ?? [];
    return relationships.filter((relationship) => relationship.source?.id === sourceRefId &&
        relationship.target?.id === targetRefId &&
        relationship.id !== currentRelationshipRef);
}
