// Generated by scripts/relationship-semantic-projection.mts from src/language/relationship-decisions.mts.
// Public-source reviewed ArchiMate 3.2 rows only; do not edit by hand.
export interface RelationshipSemanticProjectionRow {
  archimateVersion: '3.2';
  sourceType: string;
  relationshipType: string;
  targetType: string;
  decision: 'allowed' | 'disallowed';
  evidenceSourceId: 'opengroup-archimate-3.2-reference-cards';
  interpretation?: string;
}

export const RELATIONSHIP_SEMANTIC_ROWS: ReadonlyArray<RelationshipSemanticProjectionRow>;
