// @ts-expect-error Node APIs are used only by this repository maintenance script.
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
// @ts-expect-error Node path APIs are used only by this repository maintenance script.
import path from 'node:path';
// @ts-expect-error Node URL APIs are used only by this repository maintenance script.
import { fileURLToPath } from 'node:url';
// @ts-expect-error Node process APIs are used only by this repository maintenance script.
import { execFileSync } from 'node:child_process';
// @ts-expect-error Node temp APIs are used only by this repository maintenance script.
import { tmpdir } from 'node:os';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = path.join(root, 'lib/util/RelationshipUtil.mts');
const outputPath = path.join(root, 'lib/util/RelationshipUtil.js');

async function render() {
  const temporaryDirectory = await mkdtemp(path.join(tmpdir(), 'archimate-relationship-util-'));
  try {
    execFileSync(process.execPath, [
      path.join(root, 'node_modules/typescript/bin/tsc'),
      '--ignoreConfig',
      sourcePath,
      '--target', 'ES2022',
      '--module', 'ESNext',
      '--moduleResolution', 'Bundler',
      '--strict',
      '--skipLibCheck',
      '--noEmit', 'false',
      '--outDir', temporaryDirectory
    ], { cwd: root, stdio: 'pipe' });
    const compiledPath = path.join(temporaryDirectory, 'RelationshipUtil.mjs');
    const compiled = await readFile(compiledPath, 'utf8');
    return `// Generated by scripts/build-legacy-relationship-util.mts from lib/util/RelationshipUtil.mts.\n// Do not edit by hand; run npm run generate:legacy-relationship-util.\n${compiled}`;
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

async function main() {
  const mode = process.argv[2];
  if (mode === '--write') {
    await writeFile(outputPath, await render(), 'utf8');
    return;
  }
  if (mode !== '--check') throw new Error('Usage: node scripts/build-legacy-relationship-util.mts --check|--write');

  const [expected, actual] = await Promise.all([render(), readFile(outputPath, 'utf8')]);
  if (expected !== actual) throw new Error('Generated legacy relationship utility is stale; run npm run generate:legacy-relationship-util.');
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : 'Relationship utility generation failed.'}\n`);
  process.exitCode = 1;
});
