// SYNTHETIC/public-source projection generation: no architecture model data is read.
// @ts-expect-error Node APIs are used only by this repository maintenance script.
import { readFile, writeFile } from 'node:fs/promises';
// @ts-expect-error Node path APIs are used only by this repository maintenance script.
import path from 'node:path';
// @ts-expect-error Node URL APIs are used only by this repository maintenance script.
import { fileURLToPath } from 'node:url';
import { RELATIONSHIP_SEMANTIC_ROWS } from '../src/language/relationship-decisions.mts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(root, 'lib/util/relationship-semantic-projection.generated.mjs');
const declarationPath = path.join(root, 'lib/util/relationship-semantic-projection.generated.d.mts');
const generated = `// Generated by scripts/relationship-semantic-projection.mts from src/language/relationship-decisions.mts.\n// Public-source reviewed ArchiMate 3.2 rows only; do not edit by hand.\nexport const RELATIONSHIP_SEMANTIC_ROWS = Object.freeze(${JSON.stringify(RELATIONSHIP_SEMANTIC_ROWS, null, 2)}.map((row) => Object.freeze(row)));\n`;
const declaration = `// Generated by scripts/relationship-semantic-projection.mts from src/language/relationship-decisions.mts.\n// Public-source reviewed ArchiMate 3.2 rows only; do not edit by hand.\nexport interface RelationshipSemanticProjectionRow {\n  archimateVersion: '3.2';\n  sourceType: string;\n  relationshipType: string;\n  targetType: string;\n  decision: 'allowed' | 'disallowed';\n  evidenceSourceId: 'opengroup-archimate-3.2-reference-cards';\n  interpretation?: string;\n}\n\nexport const RELATIONSHIP_SEMANTIC_ROWS: ReadonlyArray<RelationshipSemanticProjectionRow>;\n`;

async function main() {
  const mode = process.argv[2];
  if (mode === '--write') {
    await Promise.all([
      writeFile(outputPath, generated, 'utf8'),
      writeFile(declarationPath, declaration, 'utf8')
    ]);
    return;
  }
  if (mode !== '--check') throw new Error('Usage: node scripts/relationship-semantic-projection.mts --check|--write');

  const [actual, actualDeclaration] = await Promise.all([
    readFile(outputPath, 'utf8'),
    readFile(declarationPath, 'utf8')
  ]);
  if (actual !== generated || actualDeclaration !== declaration) {
    throw new Error('Legacy relationship projection is stale; run npm run generate:relationship-projection.');
  }
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : 'Projection check failed.'}\n`);
  process.exitCode = 1;
});
